### PR TITLE
Remove deferred compute architecture for causal and counterfactual

### PR DESCRIPTION
**Pull request by gregorybchris**
Changes `add()/compute()` design of managers to be `compute()` only. The computed insights will still be saved to the managers for `get()` and `list()` to work as previously designed.

### CODE REVIEW

**Comment by imatiach-msft** [comment]
@gregorybchris I thought we weren't going to do this for the initial release?  Didn't we want to discuss this more with PM, or do we have agreement on this revised API now?  Even if we have agreement, shouldn't we wait until we finish the end to end notebook, and then we can plan/discuss the next steps?

**Comment by gregorybchris** [comment]
> @gregorybchris I thought we weren't going to do this for the initial release? Didn't we want to discuss this more with PM, or do we have agreement on this revised API now? Even if we have agreement, shouldn't we wait until we finish the end to end notebook, and then we can plan/discuss the next steps?

I got PM approval on the design doc (both of them) and it seemed from the chat like your concerns had been addressed. I'm open to holding off, but not sure I totally understand your concern.

**Comment by imatiach-msft** [comment]
@gregorybchris I guess my concern is we are making this API change too quickly, and there are a lot of moving parts already.  We want to hit the tight deadline and this is adding extra work that might cause it to slip.

**Comment by imatiach-msft** [comment]
@gregorybchris we discussed and it seems like this is an important change to get in sooner rather than later

**Comment by gaugup** [comment]
> @gregorybchris I guess my concern is we are making this API change too quickly, and there are a lot of moving parts already. We want to hit the tight deadline and this is adding extra work that might cause it to slip.

This is a major change. I fear that other managers may not align by June 30th. This change even though approved by PMs should have been made earlier.

**Pull request closed without merging**
