### PR TITLE
Add empty causal and counterfactual projects

### LINKED ISSUE #412: MAD: create a stub for what-if based on current local explanation tab
This is a prereq for the future what-if tab

### PR DESCRIPTION
**Pull request by romanlutz**
closes #412

### CODE REVIEW

**Review by imatiach-msft — APPROVED** [review]

**Comment by imatiach-msft** [comment]
this looks like the wrong issue?

> closes #412

**Review by xuke444 — APPROVED** [review]

**Comment by romanlutz** [comment]
> this looks like the wrong issue?
> 
> > closes #412

It's actually the correct one. By "stub" I meant "empty project". I asked @xuke444 yesterday whether I should make it be exactly like the current local explanation tab from error analysis since that contains one version of what-if, so it would provide a starting point. He said empty is better and @zhb000 / @zhb789 (I think both of these are Bo) will take it from there.

**Comment by imatiach-msft** [comment]
that issue is for what if tab though, not causal and counterfactual?  maybe the issue is just worded in a confusing way

**Comment by romanlutz** [comment]
> that issue is for what if tab though, not causal and counterfactual? maybe the issue is just worded in a confusing way

Sorry, somehow this didn't show when I completed it. What-if is the same as counterfactuals. I do hope that we can refactor out the corresponding pieces from `interpret` and `error-analysis`, but I don't know if that's in scope for @zhb000 / @zhb789

**Pull request merged**
