### PR TITLE
Update model analysis notebook to use Boston housing dataset

### PR DESCRIPTION
**Pull request by gregorybchris**

### CODE REVIEW

**Review by xuke444 — APPROVED** [review]

**Comment by xuke444** [comment]
counterfactual breaks

**Review by xuke444 — COMMENTED** [review]
counterfactual breaks

**Comment by imatiach-msft** [comment]
@gregorybchris I'm just wondering why are we doing this as opposed to adding another notebook for regression scenario?

**Comment by gregorybchris** [comment]
> @gregorybchris I'm just wondering why are we doing this as opposed to adding another notebook for regression scenario?

That's a good point. I'll do that; can't hurt to have two notebooks

**Pull request closed without merging**
