### PR TITLE
Update graphviz dependency test

### PR DESCRIPTION
**Pull request by gregorybchris**

### CODE REVIEW

**Review by gaugup — APPROVED** [review]

**Comment by imatiach-msft** [comment]
@gregorybchris can this PR be closed?

**Comment by gregorybchris** [comment]
> @gregorybchris can this PR be closed?

Looks like it's out of sync with main. I'll checkin when all tests pass again

**Comment by imatiach-msft** [comment]
I thought this should be closed in favor of:
https://github.com/microsoft/responsible-ai-widgets/pull/631
which has been merged?  Or do we still want this change to the tests?

**Comment by gregorybchris** [comment]
> I thought this should be closed in favor of:
> #631
> which has been merged? Or do we still want this change to the tests?

Personally I still would like to split this out, but it certainly is personal preference. The PR isn't needed

**Review by imatiach-msft — APPROVED** [review]

**Pull request merged**
